FROM ruby:3.4.2

# 必要なパッケージ
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  postgresql-client \
  && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリ
WORKDIR /app

# Gemfile を先にコピー（キャッシュ効かせる）
COPY Gemfile Gemfile.lock ./

# bundler & gem install
RUN gem install bundler && bundle install

# アプリ本体
COPY . .

# Rails 用ポート
EXPOSE 3000

# 開発環境で起動
CMD ["bin/rails", "server", "-b", "0.0.0.0"]